import { 
    Container, 
    Header,
    Aside,
    Main,
    Footer,
    Menu,
    Submenu,
    MenuItem,
    MenuItemGroup,
    Table,
    TableColumn,
    Row,
    Col,
    Input,
    Select,
    Option,
    Button,
    Pagination,
    Message,
    MessageBox,
    Dialog,
    Form,
    FormItem,
    Avatar,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Tabs,
    TabPane,
    Empty,
    Radio,
    Tag,
    Card,
    Descriptions,
    DescriptionsItem,
    Switch,
    Calendar,
    Carousel,
    CarouselItem
} from 'element-ui'

const element = {
    install: function(Vue) {
        Vue.use(Container),
        Vue.use(Header),
        Vue.use(Aside),
        Vue.use(Main),
        Vue.use(Footer),
        Vue.use(Menu),
        Vue.use(Submenu),
        Vue.use(MenuItem),
        Vue.use(MenuItemGroup),
        Vue.use(Table),
        Vue.use(TableColumn),
        Vue.use(Row),
        Vue.use(Col),
        Vue.use(Input),
        Vue.use(Select),
        Vue.use(Option),
        Vue.use(Button),
        Vue.use(Pagination),
        Vue.use(Dialog),
        Vue.use(Form),
        Vue.use(FormItem),
        Vue.use(Avatar),
        Vue.use(Dropdown),
        Vue.use(DropdownMenu),
        Vue.use(DropdownItem),
        Vue.use(Tabs),
        Vue.use(TabPane),
        Vue.use(Empty),
        Vue.use(Radio),
        Vue.use(Tag),
        Vue.use(Card),
        Vue.use(Descriptions),
        Vue.use(DescriptionsItem),
        Vue.use(Switch),
        Vue.use(Calendar),
        Vue.use(Carousel),
        Vue.use(CarouselItem)

        Vue.prototype.$message = Message
        Vue.prototype.$msgbox = MessageBox
        Vue.prototype.$confirm = MessageBox.confirm

    }
}

export default element
