--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2025/5/11 22:01:51
-- Server version: 8.0.18
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE teachingmanager;

--
-- Drop table `administrator`
--
DROP TABLE IF EXISTS administrator;

--
-- Drop table `course_switch`
--
DROP TABLE IF EXISTS course_switch;

--
-- Drop table `course`
--
DROP TABLE IF EXISTS course;

--
-- Drop table `course_status`
--
DROP TABLE IF EXISTS course_status;

--
-- Drop table `course_application`
--
DROP TABLE IF EXISTS course_application;

--
-- Drop table `place`
--
DROP TABLE IF EXISTS place;

--
-- Drop table `courses_students`
--
DROP TABLE IF EXISTS courses_students;

--
-- Drop table `student`
--
DROP TABLE IF EXISTS student;

--
-- Drop table `course_examination`
--
DROP TABLE IF EXISTS course_examination;

--
-- Drop table `operation`
--
DROP TABLE IF EXISTS operation;

--
-- Drop table `teacher`
--
DROP TABLE IF EXISTS teacher;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE teachingmanager;

--
-- Create table `department`
--
CREATE TABLE department (
  department_id int NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL COMMENT '学院名称',
  PRIMARY KEY (department_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '学院信息表';

--
-- Create index `name_UNIQUE` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX name_UNIQUE (name);

--
-- Create table `teacher`
--
CREATE TABLE teacher (
  teacher_id int NOT NULL AUTO_INCREMENT,
  name varchar(15) DEFAULT NULL COMMENT '教师姓名',
  teacher_number varchar(45) DEFAULT NULL COMMENT '教师工号',
  department_id int DEFAULT NULL COMMENT '学院id',
  date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后操作时间',
  password varchar(45) DEFAULT '123456' COMMENT '密码',
  PRIMARY KEY (teacher_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '教师信息表';

--
-- Create index `teacher_department_idx` on table `teacher`
--
ALTER TABLE teacher
ADD INDEX teacher_department_idx (department_id);

--
-- Create index `teacher_number_UNIQUE` on table `teacher`
--
ALTER TABLE teacher
ADD UNIQUE INDEX teacher_number_UNIQUE (teacher_number);

--
-- Create foreign key
--
ALTER TABLE teacher
ADD CONSTRAINT teacher_department FOREIGN KEY (department_id)
REFERENCES department (department_id);

--
-- Create table `operation`
--
CREATE TABLE operation (
  operation_id int NOT NULL AUTO_INCREMENT,
  name varchar(30) DEFAULT NULL COMMENT '操作名称',
  PRIMARY KEY (operation_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '用户操作信息表，如新增，删除，修改等';

--
-- Create table `course_examination`
--
CREATE TABLE course_examination (
  course_examination_id int NOT NULL AUTO_INCREMENT,
  name varchar(20) DEFAULT NULL COMMENT '审批流程中的名称',
  PRIMARY KEY (course_examination_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程审批表';

--
-- Create index `name_UNIQUE` on table `course_examination`
--
ALTER TABLE course_examination
ADD UNIQUE INDEX name_UNIQUE (name);

--
-- Create table `student`
--
CREATE TABLE student (
  student_id int NOT NULL AUTO_INCREMENT,
  student_number varchar(45) DEFAULT NULL COMMENT '学生学号',
  name varchar(15) DEFAULT NULL COMMENT '学生姓名',
  student_class varchar(45) DEFAULT NULL COMMENT '学生班级',
  date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '最后操作时间',
  password varchar(45) DEFAULT '123456' COMMENT '密码',
  PRIMARY KEY (student_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 31,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '学生信息表';

--
-- Create index `student_number_UNIQUE` on table `student`
--
ALTER TABLE student
ADD UNIQUE INDEX student_number_UNIQUE (student_number);

--
-- Create table `courses_students`
--
CREATE TABLE courses_students (
  courses_students_id int NOT NULL AUTO_INCREMENT,
  course_id int DEFAULT NULL COMMENT '课程id',
  student_id int DEFAULT NULL COMMENT '学生id',
  score float DEFAULT NULL COMMENT '课程成绩',
  PRIMARY KEY (courses_students_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程与学生之间的选择（学生选课，课程被选）';

--
-- Create index `students_idx` on table `courses_students`
--
ALTER TABLE courses_students
ADD INDEX students_idx (student_id);

--
-- Create foreign key
--
ALTER TABLE courses_students
ADD CONSTRAINT students FOREIGN KEY (student_id)
REFERENCES student (student_id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `place`
--
CREATE TABLE place (
  place_id int NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL COMMENT '地点名称',
  PRIMARY KEY (place_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '地点';

--
-- Create table `course_application`
--
CREATE TABLE course_application (
  course_application_id int NOT NULL AUTO_INCREMENT,
  teacher_id int DEFAULT NULL COMMENT '教师的id(申请人)',
  course_id int DEFAULT NULL COMMENT '课程id',
  course_name varchar(45) DEFAULT NULL COMMENT '课程名称',
  course_credit varchar(5) DEFAULT NULL COMMENT '学分',
  course_hour varchar(5) DEFAULT NULL COMMENT '学时',
  course_time varchar(45) DEFAULT NULL COMMENT '上课时间（可能需要改进）',
  course_place_id int DEFAULT NULL COMMENT '上课地点id',
  course_description text DEFAULT NULL COMMENT '课程描述',
  course_examination_id int DEFAULT NULL COMMENT '课程审批状态',
  operation_id int DEFAULT NULL COMMENT '申请的操作，有新增，修改和删除。',
  date_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间',
  PRIMARY KEY (course_application_id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程申请记录表';

--
-- Create index `application_examination_idx` on table `course_application`
--
ALTER TABLE course_application
ADD INDEX application_examination_idx (course_examination_id);

--
-- Create index `application_operation_idx` on table `course_application`
--
ALTER TABLE course_application
ADD INDEX application_operation_idx (operation_id);

--
-- Create index `application_place_idx` on table `course_application`
--
ALTER TABLE course_application
ADD INDEX application_place_idx (course_place_id);

--
-- Create index `application_teacher_idx` on table `course_application`
--
ALTER TABLE course_application
ADD INDEX application_teacher_idx (teacher_id);

--
-- Create index `course_id_UNIQUE` on table `course_application`
--
ALTER TABLE course_application
ADD UNIQUE INDEX course_id_UNIQUE (course_id);

--
-- Create foreign key
--
ALTER TABLE course_application
ADD CONSTRAINT application_examination FOREIGN KEY (course_examination_id)
REFERENCES course_examination (course_examination_id);

--
-- Create foreign key
--
ALTER TABLE course_application
ADD CONSTRAINT application_operation FOREIGN KEY (operation_id)
REFERENCES operation (operation_id);

--
-- Create foreign key
--
ALTER TABLE course_application
ADD CONSTRAINT application_place FOREIGN KEY (course_place_id)
REFERENCES place (place_id) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE course_application
ADD CONSTRAINT application_teacher FOREIGN KEY (teacher_id)
REFERENCES teacher (teacher_id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `course_status`
--
CREATE TABLE course_status (
  course_status_id int NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL COMMENT '状态名称',
  PRIMARY KEY (course_status_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程状态';

--
-- Create table `course`
--
CREATE TABLE course (
  course_id int NOT NULL AUTO_INCREMENT,
  name varchar(30) DEFAULT NULL COMMENT '课程名称',
  teacher_id int DEFAULT NULL COMMENT '任课教师',
  credit varchar(5) DEFAULT NULL COMMENT '学分',
  hour varchar(20) DEFAULT NULL COMMENT '学时',
  time varchar(45) DEFAULT NULL COMMENT '上课时间(可能需要改进)',
  place_id int DEFAULT NULL COMMENT '地点id',
  description text DEFAULT NULL COMMENT '简介描述',
  course_status_id int DEFAULT NULL COMMENT '课程状态',
  is_delete int DEFAULT 0 COMMENT '0代表没有删除，1代表已经删除了。',
  PRIMARY KEY (course_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程信息表';

--
-- Create index `course_place_idx` on table `course`
--
ALTER TABLE course
ADD INDEX course_place_idx (place_id);

--
-- Create index `course_status_idx` on table `course`
--
ALTER TABLE course
ADD INDEX course_status_idx (course_status_id);

--
-- Create index `course_teacher_idx` on table `course`
--
ALTER TABLE course
ADD INDEX course_teacher_idx (teacher_id);

--
-- Create foreign key
--
ALTER TABLE course
ADD CONSTRAINT course_place FOREIGN KEY (place_id)
REFERENCES place (place_id) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE course
ADD CONSTRAINT course_status FOREIGN KEY (course_status_id)
REFERENCES course_status (course_status_id);

--
-- Create foreign key
--
ALTER TABLE course
ADD CONSTRAINT course_teacher FOREIGN KEY (teacher_id)
REFERENCES teacher (teacher_id) ON DELETE SET NULL ON UPDATE CASCADE;

--
-- Create table `course_switch`
--
CREATE TABLE course_switch (
  course_switch_id int NOT NULL AUTO_INCREMENT,
  status int NOT NULL COMMENT '1代表启动选课，0代表关闭选课',
  PRIMARY KEY (course_switch_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '课程的开启与关闭表';

--
-- Create table `administrator`
--
CREATE TABLE administrator (
  administrator_id int NOT NULL AUTO_INCREMENT,
  name varchar(15) DEFAULT NULL COMMENT '姓名',
  account varchar(45) DEFAULT NULL COMMENT '账号',
  password varchar(45) DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (administrator_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = '管理员（教务处）';

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
(2, '人文学院'),
(4, '商学院'),
(3, '土木工程学院'),
(5, '地球信息与科学工程学院'),
(6, '外国语学院'),
(7, '艺术学院'),
(1, '计算机科学与工程学院'),
(8, '马克思主义学院');

-- 
-- Dumping data for table operation
--
INSERT INTO operation VALUES
(1, '新增'),
(2, '修改'),
(3, '删除');

-- 
-- Dumping data for table course_examination
--
INSERT INTO course_examination VALUES
(2, '已通过'),
(1, '待审批'),
(3, '未通过');

-- 
-- Dumping data for table student
--
INSERT INTO student VALUES
(1, '10000001', '王小王', '一班', '2025-05-11 21:15:05', '123456'),
(22, '10000002', '李四', '一班', '2025-05-11 21:22:03', '123456'),
(23, '10000003', '王五', '二班', '2025-05-11 21:22:03', '123456'),
(24, '10000004', '赵六', '二班', '2025-05-11 21:22:03', '123456'),
(25, '10000005', '孙七', '三班', '2025-05-11 21:22:03', '123456'),
(26, '10000006', '周八', '三班', '2025-05-11 21:22:03', '123456'),
(27, '10000007', '吴九', '四班', '2025-05-11 21:22:03', '123456'),
(28, '10000008', '郑十', '四班', '2025-05-11 21:22:03', '123456'),
(29, '10000009', '冯十一', '五班', '2025-05-11 21:22:03', '123456'),
(30, '10000010', '陈十二', '五班', '2025-05-11 21:22:03', '123456');

-- 
-- Dumping data for table teacher
--
INSERT INTO teacher VALUES
(1, '李峰', '30000001', 6, '2025-05-11 21:23:07', '123456'),
(2, '王海', '30000002', 3, '2025-05-11 21:23:20', '123456'),
(3, '李东旭', '30000003', 7, '2025-05-11 21:56:11', '123456');

-- 
-- Dumping data for table place
--
INSERT INTO place VALUES
(1, '逸夫楼429'),
(2, '第八教学楼211'),
(3, '第九教学楼412'),
(4, '第九教学楼410'),
(5, '第九教学楼312'),
(6, '第九教学楼520'),
(7, '物理楼318'),
(8, '东附楼201'),
(9, '逸夫楼520'),
(10, '逸夫楼211');

-- 
-- Dumping data for table course_status
--
INSERT INTO course_status VALUES
(1, '等待课程安排'),
(2, '可选'),
(3, '已结课'),
(4, '授课中'),
(5, '待选');

-- 
-- Dumping data for table course_switch
--
INSERT INTO course_switch VALUES
(1, 0);

-- 
-- Dumping data for table course_application
--
-- Table teachingmanager.course_application does not contain any data (it is empty)

-- 
-- Dumping data for table courses_students
--
-- Table teachingmanager.courses_students does not contain any data (it is empty)

-- 
-- Dumping data for table course
--
INSERT INTO course VALUES
(1, '土木工程', 2, '4.0', '64', '星期五第3，4节课', 3, '土木工程', 5, 0),
(2, '大学英语', 1, '4.0', '64', '星期三3,4节', 3, '大学英语', 5, 0),
(3, '艺术鉴赏', 3, '4.0', '32', '星期二第1,2节', 4, '艺术鉴赏', 5, 0);

-- 
-- Dumping data for table administrator
--
INSERT INTO administrator VALUES
(1, '管理员', 'root', '123456');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;